### ISSUE TITLE
onSave is not being called

### ISSUE THREAD

**Issue by davoutuk** [BruckCode/chips_input_autocomplete#1]
I'm trying to use your ChipsInputAutocomplete widget inside my Flutter form,  and the ChipsInputAutocomplete 'onSave' method is never called.

**Comment by EmilyMoonstone** [comment]
You are right, the behavior inside a form widget wasn't correct. I changed it work properly as a FormField. With version 1.2.0 it should be now calling the `onSaved` method.
Please upgrade to 1.2.0 and tell me if it is still not working.
